#!/usr/bin/env node
// build-page.mjs — the brain's block on the page and in the README, generated from the sealed
// pre-registration and the committed run by brain.mjs's own grader. Never typed; CI rebuilds it and
// fails if the committed page differs.
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { scoreAnswers, judgeBrain } from './brain.mjs';

const ROOT = dirname(fileURLToPath(import.meta.url));
const read = (f) => readFileSync(join(ROOT, f), 'utf8').replace(/\r\n/g, '\n');
const json = (f) => (existsSync(join(ROOT, f)) ? JSON.parse(read(f)) : null);
const esc = (s) => String(s ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
const pre = json('data/brain-prereg.json'), run = json('data/brain-run.json');

let html = '', md = '';
if (!pre) { html = '<p class="muted">Not sealed yet.</p>'; md = 'Not sealed yet.'; }
else if (!run) {
  html = '<p class="muted">Sealed before the cockpit was asked anything (<code>data/brain-prereg.json</code>): ' + pre.questions.length + ' questions, bars ' + pre.bars.withAtLeast + ' with and at most ' + pre.bars.withoutAtMost + ' without. Being measured; the result lands here whichever way it goes.</p>';
  md = 'Sealed before the cockpit was asked anything (`data/brain-prereg.json`); being measured.';
} else {
  const withBrain = scoreAnswers(pre.questions, run.arms.with.answers.map((a) => a.reply));
  const without = scoreAnswers(pre.questions, run.arms.without.answers.map((a) => a.reply));
  const j = judgeBrain({ withBrain, without, live: { soulLive: run.live.soulLive.ok, loopCloses: run.live.loopCloses.ok }, bars: pre.bars });
  const mark = (b) => (b ? '✓' : '·');
  const secs = (arm) => Math.round(arm.answers.reduce((a, x) => a + x.ms, 0) / arm.answers.length / 100) / 10;
  html = '<p><b>' + j.passed + ' of ' + j.of + ' sealed rules held.</b> The cockpit\'s own local route (' + esc(run.arms.with.model) + ' on this machine) answered '
    + '<b>' + withBrain.right + ' of ' + withBrain.n + '</b> right with the brain and <b>' + without.right + ' of ' + without.n + '</b> without it. '
    + 'Sealed in <code>' + esc(run.sealedIn.slice(0, 7)) + '</code> before anything was asked; every reply is in <code>data/brain-run.json</code> and CI re-grades it on every push.</p>'
    + '<div class="scroll"><table><thead><tr><th>question</th><th>without</th><th>with</th></tr></thead><tbody>'
    + pre.questions.map((q, k) => '<tr><td>' + esc(q.q) + '</td><td>' + mark(without.marks[k]) + '</td><td>' + mark(withBrain.marks[k]) + '</td></tr>').join('')
    + '</tbody></table></div>'
    + '<div class="scroll"><table><thead><tr><th>sealed rule</th><th>result</th><th></th><th>predicted</th></tr></thead><tbody>'
    + j.rules.map((r) => '<tr><td>' + esc(pre.rules.find((x) => x.id === r.id).rule) + '</td><td>' + esc(r.value) + '</td><td>' + (r.pass ? 'PASS' : 'FAIL') + '</td><td>' + esc(pre.predictions[r.id]) + '</td></tr>').join('')
    + '</tbody></table></div>'
    + '<p class="muted">The soul found the new memory after ' + (run.live.soulLive.waitedMs / 1000).toFixed(1) + ' s with no restart (' + (run.live.soulLive.ok ? 'found' : 'not found') + '). '
    + 'The session-start digest named the newest build (' + esc(run.live.loopCloses.newest) + ') and the queue\'s next one. '
    + 'Average reply: ' + secs(run.arms.without) + ' s without the brain, ' + secs(run.arms.with) + ' s with it, on one laptop (a timing, not a benchmark).</p>';
  md = '**' + j.passed + ' of ' + j.of + ' sealed rules held** (sealed in `' + run.sealedIn.slice(0, 7) + '`). The cockpit\'s local route (' + run.arms.with.model + ') answered **'
    + withBrain.right + '/' + withBrain.n + '** with the brain and **' + without.right + '/' + without.n + '** without it.\n\n'
    + '| Sealed rule | Result | | Predicted |\n|---|---|---|---|\n'
    + j.rules.map((r) => '| ' + pre.rules.find((x) => x.id === r.id).rule + ' | ' + r.value + ' | ' + (r.pass ? 'PASS' : 'FAIL') + ' | ' + pre.predictions[r.id] + ' |').join('\n');
}

const splice = (file, open, close, body) => {
  const s = read(file);
  const a = s.indexOf(open), b = s.indexOf(close);
  if (a < 0 || b < 0) throw new Error('the brain markers are missing from ' + file);
  writeFileSync(join(ROOT, file), s.slice(0, a + open.length) + '\n' + body + '\n' + s.slice(b));
};
splice('index.html', '<!-- ⟦BRAIN-BEGIN⟧ generated by build-page.mjs -->', '<!-- ⟦BRAIN-END⟧ -->', html);
splice('README.md', '<!-- ⟦BRAIN-BEGIN⟧ generated by build-page.mjs -->', '<!-- ⟦BRAIN-END⟧ -->', md);
console.log('page built · ' + (run ? 'measured' : pre ? 'sealed' : 'unsealed'));
