#!/usr/bin/env node
// build-page.mjs — the brain's block on the page and in the README, generated from the sealed
// pre-registration and the committed run by brain.mjs's own grader. Never typed; CI rebuilds it and
// fails if the committed page differs.
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { scoreAnswers, judgeBrain, judgeFix } from '../brain.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const read = (f) => readFileSync(join(ROOT, f), 'utf8').replace(/\r\n/g, '\n');
const json = (f) => (existsSync(join(ROOT, f)) ? JSON.parse(read(f)) : null);
const esc = (s) => String(s ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
const pre = json('data/brain-prereg.json'), run = json('data/brain-run.json');

let html = '', md = '';
if (!pre) { html = '<p class="muted">Not sealed yet.</p>'; md = 'Not sealed yet.'; }
else if (!run) {
  html = '<p class="muted">Sealed before the cockpit was asked anything (<code>data/brain-prereg.json</code>): ' + pre.questions.length + ' questions, bars ' + pre.bars.withAtLeast + ' with and at most ' + pre.bars.withoutAtMost + ' without. Being measured; the result lands here whichever way it goes.</p>';
  md = 'Sealed before the cockpit was asked anything (`data/brain-prereg.json`); being measured.';
} else {
  const withBrain = scoreAnswers(pre.questions, run.arms.with.answers.map((a) => a.reply));
  const without = scoreAnswers(pre.questions, run.arms.without.answers.map((a) => a.reply));
  const j = judgeBrain({ withBrain, without, live: { soulLive: run.live.soulLive.ok, loopCloses: run.live.loopCloses.ok }, bars: pre.bars });
  const mark = (b) => (b ? '✓' : '·');
  const secs = (arm) => Math.round(arm.answers.reduce((a, x) => a + x.ms, 0) / arm.answers.length / 100) / 10;
  html = '<p><b>' + j.passed + ' of ' + j.of + ' sealed rules held.</b> The cockpit\'s own local route (' + esc(run.arms.with.model) + ' on this machine) answered '
    + '<b>' + withBrain.right + ' of ' + withBrain.n + '</b> right with the brain and <b>' + without.right + ' of ' + without.n + '</b> without it. '
    + 'Sealed in <code>' + esc(run.sealedIn.slice(0, 7)) + '</code> before anything was asked; every reply is in <code>data/brain-run.json</code> and CI re-grades it on every push.</p>'
    + '<div class="scroll"><table><thead><tr><th>question</th><th>without</th><th>with</th></tr></thead><tbody>'
    + pre.questions.map((q, k) => '<tr><td>' + esc(q.q) + '</td><td>' + mark(without.marks[k]) + '</td><td>' + mark(withBrain.marks[k]) + '</td></tr>').join('')
    + '</tbody></table></div>'
    + '<div class="scroll"><table><thead><tr><th>sealed rule</th><th>result</th><th></th><th>predicted</th></tr></thead><tbody>'
    + j.rules.map((r) => '<tr><td>' + esc(pre.rules.find((x) => x.id === r.id).rule) + '</td><td>' + esc(r.value) + '</td><td>' + (r.pass ? 'PASS' : 'FAIL') + '</td><td>' + esc(pre.predictions[r.id]) + '</td></tr>').join('')
    + '</tbody></table></div>'
    + '<p class="muted">The soul found the new memory after ' + (run.live.soulLive.waitedMs / 1000).toFixed(1) + ' s with no restart (' + (run.live.soulLive.ok ? 'found' : 'not found') + '). '
    + 'The session-start digest named the newest build (' + esc(run.live.loopCloses.newest) + ') and the queue\'s next one. '
    + 'Average reply: ' + secs(run.arms.without) + ' s without the brain, ' + secs(run.arms.with) + ' s with it, on one laptop (a timing, not a benchmark).</p>';
  md = '**' + j.passed + ' of ' + j.of + ' sealed rules held** (sealed in `' + run.sealedIn.slice(0, 7) + '`). The cockpit\'s local route (' + run.arms.with.model + ') answered **'
    + withBrain.right + '/' + withBrain.n + '** with the brain and **' + without.right + '/' + without.n + '** without it.\n\n'
    + '| Sealed rule | Result | | Predicted |\n|---|---|---|---|\n'
    + j.rules.map((r) => '| ' + pre.rules.find((x) => x.id === r.id).rule + ' | ' + r.value + ' | ' + (r.pass ? 'PASS' : 'FAIL') + ' | ' + pre.predictions[r.id] + ' |').join('\n');
}

const splice = (file, open, close, body) => {
  const s = read(file);
  const a = s.indexOf(open), b = s.indexOf(close);
  if (a < 0 || b < 0) throw new Error('the brain markers are missing from ' + file);
  writeFileSync(join(ROOT, file), s.slice(0, a + open.length) + '\n' + body + '\n' + s.slice(b));
};
splice('index.html', '<!-- ⟦BRAIN-BEGIN⟧ generated by build-page.mjs -->', '<!-- ⟦BRAIN-END⟧ -->', html);

// THE FIX PASS (2026-10-01): its own sealed block, built the same way from its pre-registration and run
const fpre = json('data/brain-fix-prereg.json'), frun = json('data/brain-fix-run.json');
let fhtml = '', fmd = '';
if (!fpre) { fhtml = '<p class="muted">Not sealed yet.</p>'; fmd = 'Not sealed yet.'; }
else if (!frun) {
  const held = fpre.questions.length - fpre.original;
  fhtml = '<p class="muted">Sealed before either arm was asked anything (<code>data/brain-fix-prereg.json</code>): the first measurement\'s ' + fpre.original + ' questions plus '
    + held + ' held out, through a frozen copy of the cockpit\'s route. Bars: ' + fpre.bars.originalAtLeast + ' of ' + fpre.original + ', '
    + fpre.bars.heldAtLeast + ' of ' + held + ' held out, and ' + fpre.bars.beatsBy + ' more right than the brain as first switched on. Being measured; the result lands here whichever way it goes.</p>';
  fmd = 'Sealed before either arm was asked anything (`data/brain-fix-prereg.json`): ' + fpre.questions.length + ' questions (' + fpre.original + ' from the first measurement, '
    + held + ' held out); being measured.';
} else {
  const sc = (a) => scoreAnswers(fpre.questions, a.answers.map((x) => x.reply));
  const v1 = sc(frun.arms.v1), v2 = sc(frun.arms.v2);
  const tools = (a) => a.answers.map((x) => x.toolCalls || 0);
  const j = judgeFix({ v1: { marks: v1.marks, tools: tools(frun.arms.v1) }, v2: { marks: v2.marks, tools: tools(frun.arms.v2) }, original: fpre.original, bars: fpre.bars });
  const mark = (b, t) => (b ? '✓' : '·') + (t ? ' <span class="muted">tool</span>' : '');
  const right = (s, from, to) => s.marks.slice(from, to).filter(Boolean).length;
  const n = fpre.questions.length, o = fpre.original;
  const secs = (arm) => Math.round(arm.answers.reduce((a, x) => a + x.ms, 0) / arm.answers.length / 100) / 10;
  fhtml = '<p><b>' + j.passed + ' of ' + j.of + ' sealed rules held.</b> Through the same frozen route (' + esc(frun.arms.v2.model) + ' on this machine), the fixed brain got <b>'
    + right(v2, 0, o) + ' of ' + o + '</b> of the first measurement\'s questions and <b>' + right(v2, o, n) + ' of ' + (n - o) + '</b> held out; the brain as first switched on got '
    + right(v1, 0, o) + ' of ' + o + ' and ' + right(v1, o, n) + ' of ' + (n - o) + '. Sealed in <code>' + esc(frun.sealedIn.slice(0, 7)) + '</code> before either arm was asked; every reply is in <code>data/brain-fix-run.json</code> and CI re-grades it on every push.</p>'
    + '<div class="scroll"><table><thead><tr><th>question</th><th>as first switched on</th><th>fixed</th></tr></thead><tbody>'
    + fpre.questions.map((q, k) => '<tr><td>' + (k === o ? '<b>held out ·</b> ' : '') + esc(q.q) + '</td><td>' + mark(v1.marks[k], frun.arms.v1.answers[k].toolCalls) + '</td><td>' + mark(v2.marks[k], frun.arms.v2.answers[k].toolCalls) + '</td></tr>').join('')
    + '</tbody></table></div>'
    + '<div class="scroll"><table><thead><tr><th>sealed rule</th><th>result</th><th></th><th>predicted</th></tr></thead><tbody>'
    + j.rules.map((r) => '<tr><td>' + esc(fpre.rules.find((x) => x.id === r.id).rule) + '</td><td>' + esc(r.value) + '</td><td>' + (r.pass ? 'PASS' : 'FAIL') + '</td><td>' + esc(fpre.predictions[r.id]) + '</td></tr>').join('')
    + '</tbody></table></div>'
    + '<p class="muted">Average reply: ' + secs(frun.arms.v1) + ' s as first switched on, ' + secs(frun.arms.v2) + ' s fixed, on one laptop (a timing, not a benchmark). Disclosed before the run: '
    + fpre.disclosures.map(esc).join(' ') + '</p>';
  fmd = '**' + j.passed + ' of ' + j.of + ' sealed rules held** (sealed in `' + frun.sealedIn.slice(0, 7) + '`). The fixed brain: **' + right(v2, 0, o) + '/' + o + '** of the first measurement\'s questions, **'
    + right(v2, o, n) + '/' + (n - o) + '** held out. As first switched on: ' + right(v1, 0, o) + '/' + o + ' and ' + right(v1, o, n) + '/' + (n - o) + '.\n\n'
    + '| Sealed rule | Result | | Predicted |\n|---|---|---|---|\n'
    + j.rules.map((r) => '| ' + fpre.rules.find((x) => x.id === r.id).rule + ' | ' + r.value + ' | ' + (r.pass ? 'PASS' : 'FAIL') + ' | ' + fpre.predictions[r.id] + ' |').join('\n');
}
splice('index.html', '<!-- ⟦FIX-BEGIN⟧ generated by build-page.mjs -->', '<!-- ⟦FIX-END⟧ -->', fhtml);
splice('README.md', '<!-- ⟦FIX-BEGIN⟧ generated by build-page.mjs -->', '<!-- ⟦FIX-END⟧ -->', fmd);
splice('README.md', '<!-- ⟦BRAIN-BEGIN⟧ generated by build-page.mjs -->', '<!-- ⟦BRAIN-END⟧ -->', md);
// SIMON'S PATTERN (2026-10-01): its own sealed block — aggregates only; the words never leave his machine
const { gradePattern } = await import('./pattern-measure.mjs');
const ppre = json('data/pattern-prereg.json'), prun = json('data/pattern-run.json');
let phtml = '', pmd = '';
if (!ppre) { phtml = '<p class="muted">Not sealed yet.</p>'; pmd = 'Not sealed yet.'; }
else if (!prun) {
  phtml = '<p class="muted">Sealed before any held-out decision was scored (<code>data/pattern-prereg.json</code>): the profile learns from decisions before '
    + esc(ppre.data.split.trainBefore) + ' and predicts those from ' + esc(ppre.data.split.heldFrom) + ' to ' + esc(ppre.data.split.heldTo) + '. Being measured; the result lands here whichever way it goes.</p>';
  pmd = 'Sealed before any held-out decision was scored (`data/pattern-prereg.json`); being measured.';
} else {
  const g = gradePattern(ppre, prun);
  const j = g.judged, s = g.summary;
  const pct = (x) => Math.round(x * 1000) / 10 + '%';
  const usual = (t) => { const c = prun.profile.byType[t]; return c ? 'go ' + c.go + ' · all ' + c.all + ' · no ' + c.no : 'never asked'; };
  phtml = '<p><b>' + j.passed + ' of ' + j.of + ' sealed rules held.</b> Learning only from his decisions before ' + esc(ppre.data.split.trainBefore) + ' (' + prun.read.train.withVerdict
    + ' with a verdict), the profile called <b>' + s.hits + ' of ' + s.n + '</b> of the held-out decisions right (' + pct(s.rate) + '); always saying go would have called ' + s.alwaysGo
    + '. Sealed in <code>' + esc(prun.sealedIn.slice(0, 7)) + '</code>; the counts and every held-out call are in <code>data/pattern-run.json</code> (no words), and CI recomputes every prediction and rate from them on every push.</p>'
    + '<div class="scroll"><table><thead><tr><th>kind of decision</th><th>his calls before (go · all · no)</th><th>predicted</th><th>held out</th><th>right</th><th>at least (95%)</th><th></th></tr></thead><tbody>'
    + s.types.map((t) => '<tr><td>' + esc(t.type) + (t.onHisKey ? ' <span class="muted">· his key</span>' : '') + '</td><td>' + esc(usual(t.type)) + '</td><td>' + esc(t.predicts) + '</td><td>' + t.n + '</td><td>'
      + (t.n ? t.hits + ' (' + pct(t.rate) + ')' : '—') + '</td><td>' + (t.n ? pct(t.low) : '—') + '</td><td>' + (t.clears && !t.onHisKey ? 'clears 95%' : '') + '</td></tr>').join('')
    + '</tbody></table></div>'
    + '<div class="scroll"><table><thead><tr><th>sealed rule</th><th>result</th><th></th><th>predicted</th></tr></thead><tbody>'
    + j.rules.map((r) => '<tr><td>' + esc(ppre.rules.find((x) => x.id === r.id).rule) + '</td><td>' + esc(r.value) + '</td><td>' + (r.pass ? 'PASS' : 'FAIL') + '</td><td>' + esc(ppre.predictions[r.id]) + '</td></tr>').join('')
    + '</tbody></table></div>'
    + '<p class="muted">' + esc(ppre.standing) + ' Read: ' + prun.read.exchanges + ' exchanges, ' + prun.read.decisions + ' decisions; held out ' + prun.read.held.decisions + ', of which '
    + prun.read.held.withVerdict + ' carried a verdict. ' + ppre.disclosures.map(esc).join(' ') + '</p>';
  pmd = '**' + j.passed + ' of ' + j.of + ' sealed rules held** (sealed in `' + prun.sealedIn.slice(0, 7) + '`). From his decisions before ' + ppre.data.split.trainBefore + ', the profile called **'
    + s.hits + '/' + s.n + '** held-out decisions right (' + pct(s.rate) + '); always saying go: ' + s.alwaysGo + '.\n\n'
    + '| Sealed rule | Result | | Predicted |\n|---|---|---|---|\n'
    + j.rules.map((r) => '| ' + ppre.rules.find((x) => x.id === r.id).rule + ' | ' + r.value + ' | ' + (r.pass ? 'PASS' : 'FAIL') + ' | ' + ppre.predictions[r.id] + ' |').join('\n');
}
splice('index.html', '<!-- ⟦PATTERN-BEGIN⟧ generated by build-page.mjs -->', '<!-- ⟦PATTERN-END⟧ -->', phtml);
splice('README.md', '<!-- ⟦PATTERN-BEGIN⟧ generated by build-page.mjs -->', '<!-- ⟦PATTERN-END⟧ -->', pmd);
console.log('page built · brain ' + (run ? 'measured' : pre ? 'sealed' : 'unsealed') + ' · fix ' + (frun ? 'measured' : fpre ? 'sealed' : 'unsealed') + ' · pattern ' + (prun ? 'measured' : ppre ? 'sealed' : 'unsealed'));
